(function () {
    var read = function (key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch (error) { return fallback; } };
    var write = function (key, value) { localStorage.setItem(key, JSON.stringify(value)); };
    var money = function (value) { return '₹' + Number(value).toFixed(2); };
    document.addEventListener('DOMContentLoaded', function () { var sellerPage = location.pathname.toLowerCase().indexOf('/sellerhub/') >= 0, publicSellerPage = /\/(index|login|register)\.html$/.test(location.pathname.toLowerCase()), adminPage = location.pathname.toLowerCase().indexOf('/admin web/') >= 0, adminLoginPage = /\/(index|login)\.html$/.test(location.pathname.toLowerCase()); if (sellerPage && !publicSellerPage && !read('activeSeller', '')) { location.href = 'index.html'; return; } if (adminPage && !adminLoginPage && !read('adminSession', false)) { location.href = 'index.html'; return; }
        var replaceBrand = function (node) { if (node.nodeType === 3) { node.nodeValue = node.nodeValue.replace(/DayliDrope/g, 'DailyDrop'); return; } if (node.nodeName === 'SCRIPT' || node.nodeName === 'STYLE') return; Array.prototype.forEach.call(node.childNodes, replaceBrand); };
        replaceBrand(document.body);
        document.querySelectorAll('.logo').forEach(function (logo) { logo.innerHTML = 'Daily<span>Drop</span>'; });
        document.title = document.title.replace(/DayliDrope/g, 'DailyDrop');
        var year = document.getElementById('currentYear'); if (year) year.textContent = new Date().getFullYear();
        var products = read('products', []), orders = read('orders', []), sellers = read('sellers', []), customers = read('customers', []), settings = read('siteSettings', { banner: { heading: 'Stock your business for the week ahead.', description: 'Fresh produce, pantry staples, and workplace essentials in one reliable weekly order.', image: '' }, categories: [{ name: 'Groceries', description: 'Kitchen staples and everyday pantry essentials.', slug: 'groceries' }, { name: 'Snacks', description: 'Small treats for every kind of break.', slug: 'snacks' }, { name: 'Beverages', description: 'Refreshments for home, work, and on the go.', slug: 'beverages' }, { name: 'Personal Care', description: 'Simple essentials for your daily routine.', slug: 'personal-care' }] });
        var adminAccount = read('adminAccount', { email: 'admin@dailydrop.com', password: '123456' }); if (adminAccount.password === 'admin123') { adminAccount.password = '123456'; write('adminAccount', adminAccount); } var activeSeller = sellers.find(function (seller) { return seller.id === read('activeSeller', ''); }); if (activeSeller && activeSeller.status === 'Pending approval' && !location.pathname.toLowerCase().endsWith('/new-seller.html') && sellerPage) { location.href = 'new-seller.html'; return; } if (activeSeller && activeSeller.status !== 'Pending approval' && location.pathname.toLowerCase().endsWith('/new-seller.html')) { location.href = 'dashboard.html'; return; } var sellersChanged = false; sellers.forEach(function (seller, index) { if (!seller.id) { seller.id = 'seller-legacy-' + index + '-' + Date.now(); sellersChanged = true; } }); if (sellersChanged) write('sellers', sellers);
        var sellerRegistration = document.getElementById('sellerRegistration'); if (sellerRegistration) sellerRegistration.addEventListener('submit', function (event) { event.preventDefault(); if (!sellerRegistration.checkValidity()) return; var data = new FormData(sellerRegistration), seller = { id: 'seller-' + Date.now(), store: data.get('store'), name: data.get('name'), email: data.get('email'), phone: data.get('phone'), password: data.get('password'), status: 'Pending approval' }; sellers.push(seller); write('sellers', sellers); write('activeSeller', seller.id); location.href = 'new-seller.html'; });
        var bannerForm = document.getElementById('bannerForm'), bannerImage = document.getElementById('bannerImage'), bannerPreview = document.getElementById('bannerImagePreview'), bannerImageData = settings.banner.image || '';
        if (bannerForm && bannerImage) { if (bannerImageData && bannerPreview) { bannerPreview.src = bannerImageData; bannerPreview.hidden = false; } bannerImage.addEventListener('change', function () { var file = bannerImage.files[0]; if (!file || file.type.indexOf('image/') !== 0) return; var reader = new FileReader(); reader.addEventListener('load', function () { var image = new Image(); image.addEventListener('load', function () { var maxWidth = 1600, scale = Math.min(1, maxWidth / image.width), canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); bannerImageData = canvas.toDataURL('image/jpeg', 0.82); if (bannerPreview) { bannerPreview.src = bannerImageData; bannerPreview.hidden = false; } }); image.src = reader.result; }); reader.readAsDataURL(file); }); var deleteBanner = document.createElement('button'); deleteBanner.className = 'btn'; deleteBanner.type = 'button'; deleteBanner.textContent = 'Delete banner image'; bannerForm.appendChild(deleteBanner); deleteBanner.addEventListener('click', function () { bannerImageData = ''; bannerImage.value = ''; settings.banner = settings.banner || {}; settings.banner.image = ''; write('siteSettings', settings); if (bannerPreview) { bannerPreview.src = ''; bannerPreview.hidden = true; } }); bannerForm.addEventListener('submit', function (event) { event.preventDefault(); if (!bannerImageData) { bannerImage.setCustomValidity('Choose an image before saving.'); bannerImage.reportValidity(); return; } bannerImage.setCustomValidity(''); settings.banner = settings.banner || {}; settings.banner.image = bannerImageData; try { write('siteSettings', settings); bannerForm.querySelector('button[type="submit"]').textContent = 'Banner image saved'; } catch (error) { bannerForm.querySelector('button[type="submit"]').textContent = 'Image too large'; } }); }
        var categoryForm = document.getElementById('categoryForm'), categoryList = document.getElementById('adminCategories'), categoryImage = document.getElementById('categoryImage'), categoryPreview = document.getElementById('categoryImagePreview'), categoryImageData = '';
        if (categoryImage) categoryImage.addEventListener('change', function () { var file = categoryImage.files[0]; if (!file || file.type.indexOf('image/') !== 0) return; var reader = new FileReader(); reader.addEventListener('load', function () { categoryImageData = reader.result; categoryPreview.src = categoryImageData; categoryPreview.hidden = false; }); reader.readAsDataURL(file); });
        var renderCategories = function () { if (!categoryList) return; categoryList.innerHTML = settings.categories.map(function (category, index) { return '<div class="admin-category">' + (category.image ? '<img class="category-admin-image" src="' + category.image + '" alt="' + category.name + '">' : '') + '<strong>' + category.name + '</strong><span>' + category.slug + '</span><button class="delete-category btn" data-index="' + index + '" type="button">Delete</button></div>'; }).join(''); document.querySelectorAll('.delete-category').forEach(function (button) { button.addEventListener('click', function () { settings.categories.splice(Number(button.dataset.index), 1); write('siteSettings', settings); renderCategories(); }); }); };
        if (categoryForm) categoryForm.addEventListener('submit', function (event) { event.preventDefault(); if (!categoryForm.checkValidity() || !categoryImageData) return; settings.categories.push({ name: categoryForm.elements.name.value, description: categoryForm.elements.description.value, slug: categoryForm.elements.slug.value.toLowerCase().replace(/\s+/g, '-'), image: categoryImageData }); write('siteSettings', settings); categoryForm.reset(); categoryImageData = ''; categoryPreview.hidden = true; renderCategories(); }); renderCategories();
        var productForm = document.getElementById('productForm'), imageInput = document.getElementById('productImage'), imagePreview = document.getElementById('imagePreview'), imageData = '';
        if (imageInput) imageInput.addEventListener('change', function () { var file = imageInput.files[0]; if (!file || file.type.indexOf('image/') !== 0) return; var reader = new FileReader(); reader.addEventListener('load', function () { imageData = reader.result; imagePreview.src = imageData; imagePreview.hidden = false; }); reader.readAsDataURL(file); });
        if (productForm) productForm.addEventListener('submit', function (event) { event.preventDefault(); if (!productForm.checkValidity() || !imageData) return; var data = new FormData(productForm); products.push({ id: 'seller-' + Date.now(), sellerId: read('activeSeller', ''), name: data.get('name'), price: Number(data.get('price')), unit: data.get('unit'), category: data.get('category'), stock: Number(data.get('stock')), image: imageData, approval: 'Pending approval' }); write('products', products); location.href = 'products.html'; });
        var sellerProducts = products.filter(function (product) { return activeSeller && product.sellerId === activeSeller.id; });
        var sellerOrdersForActiveSeller = orders.filter(function (order) { return activeSeller && (order.items || []).some(function (item) { return item.sellerId === activeSeller.id; }); });
        var productList = document.getElementById('sellerProducts');
        if (productList) productList.innerHTML = sellerProducts.length ? sellerProducts.map(function (product) { return '<article class="card"><img class="seller-product-image" src="' + product.image + '" alt="' + product.name + '"><h2>' + product.name + '</h2><p>' + money(product.price) + ' / ' + product.unit + '</p><p>Stock: ' + product.stock + ' - ' + (product.approval || 'Approved') + '</p><button class="delete-product btn" data-id="' + product.id + '" type="button">Delete</button></article>'; }).join('') : '<p>Your catalogue is empty.</p>';
        document.querySelectorAll('.delete-product').forEach(function (button) { button.addEventListener('click', function () { write('products', products.filter(function (product) { return product.id !== button.dataset.id || !activeSeller || product.sellerId !== activeSeller.id; })); location.reload(); }); });
        var sellerOrderItems = sellerOrdersForActiveSeller.reduce(function (items, order) { return items.concat(order.items || []); }, []).filter(function (item) { return activeSeller && item.sellerId === activeSeller.id; }); var refundedOrders = sellerOrdersForActiveSeller.filter(function (order) { return order.returnStatus === 'Refunded'; }), returnRequests = sellerOrdersForActiveSeller.filter(function (order) { return order.returnStatus && order.returnStatus !== 'Rejected'; }), grossSales = sellerOrderItems.reduce(function (sum, item) { return sum + Number(item.price || 0) * Number(item.quantity || 0); }, 0), refundedSales = refundedOrders.reduce(function (sum, order) { return sum + (order.items || []).filter(function (item) { return activeSeller && item.sellerId === activeSeller.id; }).reduce(function (total, item) { return total + Number(item.price || 0) * Number(item.quantity || 0); }, 0); }, 0), netSales = grossSales - refundedSales;
        var sellerBanner = document.getElementById('sellerBanner'); if (sellerBanner) sellerBanner.innerHTML = (settings.sellerBanner || settings.banner) && (settings.sellerBanner || settings.banner).image ? '<img src="' + (settings.sellerBanner || settings.banner).image + '" alt="DailyDrop seller banner">' : '<p>DailyDrop seller updates</p>'; var sellerIdentity = document.getElementById('sellerIdentity'); if (sellerIdentity) sellerIdentity.innerHTML = activeSeller ? '<h2>' + (activeSeller.store || 'Unnamed seller') + '</h2><p>' + (activeSeller.name || 'No contact name') + ' · ' + (activeSeller.email || 'No email') + '</p><p>Status: ' + (activeSeller.status || 'Approved') + '</p>' : '<p>No seller account is active. Register or log in to continue.</p>';
        var sellerProfileForm = document.getElementById('sellerProfileForm'), sellerProfileStatus = document.getElementById('sellerProfileStatus'); if (sellerProfileForm) { if (!activeSeller) { sellerProfileForm.hidden = true; sellerProfileStatus.innerHTML = '<p>No seller account is active. <a href="register.html">Register your store</a> or <a href="index.html">log in</a> first.</p>'; } else { ['store', 'name', 'email', 'phone', 'deliveryPreferences'].forEach(function (field) { sellerProfileForm.elements[field].value = activeSeller[field] || ''; }); sellerProfileStatus.innerHTML = '<p>Account status: <strong>' + (activeSeller.status || 'Approved') + '</strong></p>'; sellerProfileForm.addEventListener('submit', function (event) { event.preventDefault(); if (!sellerProfileForm.checkValidity()) return; var data = new FormData(sellerProfileForm); Object.keys(activeSeller).forEach(function (field) { if (sellerProfileForm.elements[field]) activeSeller[field] = data.get(field); }); write('sellers', sellers); document.getElementById('sellerProfileMessage').textContent = 'Profile saved'; }); } }
        var sellerStats = document.getElementById('sellerStats'); if (sellerStats) sellerStats.innerHTML = '<div class="card"><h2>' + sellerProducts.length + '</h2><p>Products</p></div><div class="card"><h2>' + sellerOrdersForActiveSeller.filter(function (order) { return order.status !== 'Delivered' && order.status !== 'Cancelled'; }).length + '</h2><p>Open orders</p></div><div class="card"><h2>' + money(netSales) + '</h2><p>Net sales</p></div><div class="card"><h2>' + money(refundedSales) + '</h2><p>Returned sales</p></div><div class="card"><h2>' + returnRequests.length + '</h2><p>Return requests</p></div>';
        var sellerReturns = document.getElementById('sellerReturns'); if (sellerReturns) sellerReturns.innerHTML = returnRequests.length ? returnRequests.slice(0, 5).map(function (order) { return '<article class="card"><strong>Order #' + order.id + '</strong><p>' + money(order.total) + ' · ' + (order.returnStatus || 'Return requested') + '</p><a class="btn" href="orders.html">Manage return</a></article>'; }).join('') : '<p>No return requests yet.</p>';
        var adminStats = document.getElementById('adminStats'); if (adminStats) adminStats.innerHTML = '<div class="card"><h2>' + customers.length + '</h2><p>Customers</p></div><div class="card"><h2>' + sellers.length + '</h2><p>Sellers</p></div><div class="card"><h2>' + orders.length + '</h2><p>Orders</p></div><div class="card"><h2>' + products.filter(function (product) { return product.approval === 'Pending approval'; }).length + '</h2><p>Pending products</p></div>';
        var adminProducts = document.getElementById('adminProducts'); if (adminProducts) adminProducts.innerHTML = products.length ? products.map(function (product) { return '<article class="card"><img class="seller-product-image" src="' + product.image + '" alt="' + product.name + '"><h2>' + product.name + '</h2><p>' + money(product.price) + ' - ' + (product.approval || 'Approved') + '</p><button class="approve-product btn" data-id="' + product.id + '" type="button">Approve</button></article>'; }).join('') : '<p>No products have been submitted.</p>';
        var adminSellers = document.getElementById('adminSellers'); if (adminSellers) adminSellers.innerHTML = sellers.length ? sellers.map(function (seller) { return '<article class="card"><h2>' + (seller.store || 'Unnamed seller') + '</h2><p>' + (seller.name || 'No contact name') + ' - ' + (seller.email || 'No email') + '</p><p>' + (seller.phone || 'No phone') + ' - ' + (seller.status || 'Approved') + '</p><p><a class="btn" href="edit-seller.html?id=' + encodeURIComponent(seller.id) + '">Edit</a> <button class="delete-seller btn" data-id="' + seller.id + '" type="button">Delete</button></p></article>'; }).join('') : '<p>No sellers have registered yet.</p>';
        document.querySelectorAll('.delete-seller').forEach(function (button) { button.addEventListener('click', function () { if (!window.confirm('Delete this seller account?')) return; write('sellers', sellers.filter(function (seller) { return seller.id !== button.dataset.id; })); if (read('activeSeller', '') === button.dataset.id) localStorage.removeItem('activeSeller'); location.reload(); }); });
        var editSellerForm = document.getElementById('editSellerForm'); if (editSellerForm) { var editSellerId = new URLSearchParams(location.search).get('id'), editSeller = sellers.find(function (seller) { return seller.id === editSellerId; }); if (!editSeller) { editSellerForm.innerHTML = '<p>Seller not found. <a href="sellers.html">Return to sellers</a></p>'; } else { ['store', 'name', 'email', 'phone', 'status'].forEach(function (field) { editSellerForm.elements[field].value = editSeller[field] || (field === 'status' ? 'Approved' : ''); }); editSellerForm.addEventListener('submit', function (event) { event.preventDefault(); if (!editSellerForm.checkValidity()) return; var data = new FormData(editSellerForm); sellers.forEach(function (seller) { if (seller.id === editSellerId) { seller.store = data.get('store'); seller.name = data.get('name'); seller.email = data.get('email'); seller.phone = data.get('phone'); seller.status = data.get('status'); } }); write('sellers', sellers); location.href = 'sellers.html'; }); } }
        document.querySelectorAll('.approve-product').forEach(function (button) { button.addEventListener('click', function () { products.forEach(function (product) { if (product.id === button.dataset.id) product.approval = 'Approved'; }); write('products', products); location.reload(); }); });
        var formatAddress = function (address) { if (!address || typeof address === 'string') return address || 'Not provided'; return [address.recipient, address.company, address.city, address.landmark, address.postalCode, address.country].filter(Boolean).join(', '); };
        var orderMarkup = function (order, includeStatus, sellerId) { var visibleItems = sellerId ? (order.items || []).filter(function (item) { return item.sellerId === sellerId; }) : (order.items || []), visibleTotal = sellerId ? visibleItems.reduce(function (sum, item) { return sum + Number(item.price || 0) * Number(item.quantity || 0); }, 0) : order.total; return '<article class="card admin-order"><h2>Order #' + order.id + '</h2><p>' + money(visibleTotal) + ' - Payment: ' + (order.payment === 'cod' ? 'Cash on Delivery' : order.payment === 'card' ? 'Card' : 'Invoice') + '</p><p>Delivery: ' + formatAddress(order.address) + '</p><p><a class="btn" href="../Customer%20Web/invoice.html?id=' + encodeURIComponent(order.id) + (sellerId ? '&sellerId=' + encodeURIComponent(sellerId) : '') + '">View invoice</a></p>' + (includeStatus ? '<select class="order-status" data-id="' + order.id + '"><option ' + (order.status === 'Processing' ? 'selected' : '') + '>Processing</option><option ' + (order.status === 'Packed' ? 'selected' : '') + '>Packed</option><option ' + (order.status === 'Shipped' ? 'selected' : '') + '>Shipped</option><option ' + (order.status === 'Delivered' ? 'selected' : '') + '>Delivered</option><option ' + (order.status === 'Cancelled' ? 'selected' : '') + '>Cancelled</option></select>' : '') + '</article>'; };
        var sellerOrders = document.getElementById('sellerOrders'); if (sellerOrders) sellerOrders.innerHTML = sellerOrdersForActiveSeller.length ? sellerOrdersForActiveSeller.map(function (order) { return orderMarkup(order, false, activeSeller.id) + '<div class="return-controls"><label>Return status <select class="return-status" data-id="' + order.id + '"><option value="" ' + (!order.returnStatus ? 'selected' : '') + '>No return</option><option ' + (order.returnStatus === 'Requested' ? 'selected' : '') + '>Requested</option><option ' + (order.returnStatus === 'Approved' ? 'selected' : '') + '>Approved</option><option ' + (order.returnStatus === 'Rejected' ? 'selected' : '') + '>Rejected</option><option ' + (order.returnStatus === 'Refunded' ? 'selected' : '') + '>Refunded</option></select></label></div>'; }).join('') : '<p>No customer orders yet.</p>';
        var adminSales = {}; orders.filter(function (order) { return order.status !== 'Cancelled'; }).forEach(function (order) { (order.items || []).forEach(function (item) { if (item.sellerId) adminSales[item.sellerId] = (adminSales[item.sellerId] || 0) + Number(item.price || 0) * Number(item.quantity || 0); }); }); var adminSalesView = document.getElementById('adminSales'); if (adminSalesView) adminSalesView.innerHTML = Object.keys(adminSales).length ? Object.keys(adminSales).map(function (sellerId) { var seller = sellers.find(function (entry) { return entry.id === sellerId; }); return '<article class="card"><h2>' + (seller ? seller.store : 'Seller') + '</h2><p>Completed sales: ' + money(adminSales[sellerId]) + '</p></article>'; }).join('') : '<p>No completed seller sales yet.</p>';
        var adminOrders = document.getElementById('adminOrders'); if (adminOrders) adminOrders.innerHTML = orders.length ? orders.slice(0, 10).map(function (order) { return orderMarkup(order, true); }).join('') : '<p>No orders have been placed yet.</p>';
        document.querySelectorAll('.order-status').forEach(function (select) { select.addEventListener('change', function () { orders.forEach(function (order) { if (order.id === select.dataset.id) order.status = select.value; }); write('orders', orders); }); });
        document.querySelectorAll('.return-status').forEach(function (select) { select.addEventListener('change', function () { orders.forEach(function (order) { if (order.id === select.dataset.id) order.returnStatus = select.value || null; }); write('orders', orders); location.reload(); }); });
        document.querySelectorAll('[data-login-target]').forEach(function (form) { form.addEventListener('submit', function (event) { event.preventDefault(); if (!form.checkValidity()) return; var email = form.elements.email.value, password = form.elements.password.value; if (form.dataset.role === 'seller') { var seller = sellers.find(function (entry) { return entry.email === email && entry.password === password; }); if (!seller) { form.elements.password.setCustomValidity('Incorrect seller email or password.'); form.reportValidity(); return; } write('activeSeller', seller.id); } else if (email !== adminAccount.email || password !== adminAccount.password) { form.elements.password.setCustomValidity('Incorrect admin email or password.'); form.reportValidity(); return; } if (form.dataset.role !== 'seller') write('adminSession', true); location.href = form.dataset.loginTarget; }); });
    });
})();
