(function () {
    var products = [
        { id: 'tomatoes', name: 'Market tomatoes', category: 'groceries', price: 18, unit: '5kg crate', stock: 24, image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=700&h=500&q=85' },
        { id: 'rice', name: 'Long grain rice', category: 'groceries', price: 32.5, unit: '10kg bag', stock: 18, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=700&h=500&q=85' },
        { id: 'coffee', name: 'House blend coffee', category: 'beverages', price: 46, unit: '1kg bag', stock: 12, image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=700&h=500&q=85' },
        { id: 'soap', name: 'Hand wash refill', category: 'personal-care', price: 14, unit: '2 litre bottle', stock: 30, image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=700&h=500&q=85' },
        { id: 'dark-chocolate', name: 'Dark chocolate bars', category: 'chocolate', price: 28, unit: '12 bar box', stock: 20, image: 'https://images.unsplash.com/photo-1575377222312-dd1a9c147b0d?auto=format&fit=crop&w=700&h=500&q=85' },
        { id: 'milk-chocolate', name: 'Milk chocolate bars', category: 'chocolate', price: 24, unit: '12 bar box', stock: 24, image: 'https://images.unsplash.com/photo-1548907040-4d42cfcaa0c8?auto=format&fit=crop&w=700&h=500&q=85' },
        { id: 'ruled-notebook', name: 'Ruled school notebooks', category: 'school-notebooks', price: 48, unit: '5 notebook pack', stock: 40, image: 'https://images.unsplash.com/photo-1531346680769-a1d79b57de5b?auto=format&fit=crop&w=700&h=500&q=85' },
        { id: 'drawing-notebook', name: 'School drawing notebooks', category: 'school-notebooks', price: 36, unit: '5 notebook pack', stock: 35, image: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=700&h=500&q=85' }
    ];
    var read = function (key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch (error) { return fallback; } };
    var write = function (key, value) { localStorage.setItem(key, JSON.stringify(value)); };
    var siteSettings = read('siteSettings', { banner: { heading: 'Stock your business for the week ahead.', description: 'Fresh produce, pantry staples, and workplace essentials in one reliable weekly order.', image: '' }, categories: [{ name: 'Groceries', description: 'Kitchen staples and everyday pantry essentials.', slug: 'groceries' }, { name: 'Snacks', description: 'Small treats for every kind of break.', slug: 'snacks' }, { name: 'Beverages', description: 'Refreshments for home, work, and on the go.', slug: 'beverages' }, { name: 'Personal Care', description: 'Simple essentials for your daily routine.', slug: 'personal-care' }, { name: 'Chocolate', description: 'Chocolate treats for every kind of break.', slug: 'chocolate' }, { name: 'School Notebooks', description: 'Everyday notebooks for school and study.', slug: 'school-notebooks' }] }), custom = read('products', []);
    if (!siteSettings.categories.some(function (category) { return category.slug === 'chocolate'; })) { siteSettings.categories.push({ name: 'Chocolate', description: 'Chocolate treats for every kind of break.', slug: 'chocolate' }); write('siteSettings', siteSettings); }
    if (!siteSettings.categories.some(function (category) { return category.slug === 'school-notebooks'; })) { siteSettings.categories.push({ name: 'School Notebooks', description: 'Everyday notebooks for school and study.', slug: 'school-notebooks' }); write('siteSettings', siteSettings); }
    custom.forEach(function (item) { if (!products.some(function (product) { return product.id === item.id; })) { products.push(item); } });
    var cart = read('cart', []);
    var money = function (value) { return '₹' + Number(value).toFixed(2); };
    var getProduct = function (id) { return products.find(function (product) { return product.id === id; }); };
    var updateCount = function () {
        var count = cart.reduce(function (total, item) { return total + item.quantity; }, 0);
        document.querySelectorAll('#cartCount').forEach(function (node) { node.textContent = count; });
        write('cart', cart);
    };
    var addToCart = function (id, quantity) {
        var product = getProduct(id); if (!product) return;
        var item = cart.find(function (entry) { return entry.id === id; });
        if (item) item.quantity = Math.min(product.stock, item.quantity + quantity); else cart.push({ id: id, quantity: Math.min(product.stock, quantity) });
        updateCount();
    };
    var productCard = function (product) {
        return '<article class="product-card"><img class="product-art" src="' + product.image + '" alt="' + product.name + '"><p class="product-type">' + product.category.replace('-', ' ') + '</p><h3>' + product.name + '</h3><div class="product-meta"><strong>' + money(product.price) + ' <small>/ ' + product.unit + '</small></strong><button class="btn add-product" data-product-id="' + product.id + '" type="button">Add</button></div></article>';
    };
    document.addEventListener('DOMContentLoaded', function () {
        var replaceBrand = function (node) { if (node.nodeType === 3) { node.nodeValue = node.nodeValue.replace(/DayliDrope/g, 'DailyDrop'); return; } if (node.nodeName === 'SCRIPT' || node.nodeName === 'STYLE') return; Array.prototype.forEach.call(node.childNodes, replaceBrand); };
        replaceBrand(document.body);
        document.querySelectorAll('.logo').forEach(function (logo) { logo.innerHTML = 'Daily<span>Drop</span>'; });
        document.title = document.title.replace(/DayliDrope/g, 'DailyDrop');
        var year = document.getElementById('currentYear'); if (year) year.textContent = new Date().getFullYear();
        var customerBanner = siteSettings.customerBanner || siteSettings.banner; if (customerBanner) { var hero = document.querySelector('.hero'), heroImage = document.querySelector('.hero-photo'); if (heroImage && customerBanner.image) heroImage.src = customerBanner.image; if (hero && customerBanner.image) { hero.classList.add('has-custom-banner'); hero.style.backgroundImage = 'url("' + customerBanner.image + '")'; } }
        var renderCategories = function (className) { return siteSettings.categories.map(function (category, index) { return '<a class="' + className + ' ' + ['tile-green', 'tile-yellow', 'tile-coral', 'tile-blue'][index % 4] + '" href="products.html?category=' + encodeURIComponent(category.slug) + '">' + (category.image ? '<img class="category-image" src="' + category.image + '" alt="' + category.name + '">' : '<div class="category-icon">▦</div>') + '<h2>' + category.name + '</h2><p>' + category.description + '</p></a>'; }).join(''); };
        var categoryList = document.getElementById('customerCategories'); if (categoryList && siteSettings.categories) categoryList.innerHTML = renderCategories('category-card');
        var homeCategoryList = document.getElementById('customerHomeCategories'); if (homeCategoryList && siteSettings.categories) homeCategoryList.innerHTML = renderCategories('category-tile');
        updateCount();
        var productList = document.getElementById('featuredProducts');
        if (productList) {
            var params = new URLSearchParams(location.search), query = (params.get('search') || '').toLowerCase(), category = params.get('category') || 'all';
            var categorySlug = function (value) { return String(value || '').toLowerCase().trim().replace(/\s+/g, '-'); };
            var visible = products.filter(function (product) { return (category === 'all' || categorySlug(product.category) === categorySlug(category)) && product.name.toLowerCase().indexOf(query) >= 0; });
            productList.innerHTML = visible.length ? visible.map(productCard).join('') : '<p>No products match your search.</p>';
            var categoryOptions = (siteSettings.categories || []).map(function (item) { return '<option value="' + categorySlug(item.slug || item.name) + '">' + item.name + '</option>'; }).join('');
            productList.insertAdjacentHTML('beforebegin', '<div class="shop-controls"><input id="catalogueSearch" type="search" placeholder="Search products" value="' + (params.get('search') || '') + '"><select id="categoryFilter"><option value="all">All categories</option>' + categoryOptions + '</select><select id="sortProducts"><option value="name">Sort: name</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>');
            document.getElementById('catalogueSearch').addEventListener('keydown', function (event) { if (event.key === 'Enter') location.href = 'products.html?search=' + encodeURIComponent(event.target.value); });
            document.getElementById('categoryFilter').value = category; document.getElementById('categoryFilter').addEventListener('change', function (event) { location.href = 'products.html?category=' + event.target.value; });
            document.getElementById('sortProducts').addEventListener('change', function (event) { var cards = visible.slice().sort(function (a, b) { return event.target.value === 'low' ? a.price - b.price : event.target.value === 'high' ? b.price - a.price : a.name.localeCompare(b.name); }); productList.innerHTML = cards.map(productCard).join(''); });
        }
        var detail = document.getElementById('productDetail');
        if (detail) { var product = getProduct(new URLSearchParams(location.search).get('id')) || products[0]; detail.innerHTML = '<img class="detail-image" src="' + product.image + '" alt="' + product.name + '"><div><p class="section-label">' + product.category.replace('-', ' ') + '</p><h1>' + product.name + '</h1><p>Reliable quality for your next business restock. Available stock: ' + product.stock + '.</p><h2>' + money(product.price) + ' <small>/ ' + product.unit + '</small></h2><label>Quantity <input id="detailQuantity" type="number" min="1" max="' + product.stock + '" value="1"></label><div class="hero-actions"><button class="btn" data-product-id="' + product.id + '" id="detailAdd" type="button">Add to cart</button><button class="button button-quiet" id="wishlistToggle" type="button">♡ Wishlist</button></div></div>'; }
        var cartView = document.getElementById('cartItems');
        if (cartView) { var total = 0, validCart = cart.filter(function (item) { return getProduct(item.id); }); if (validCart.length !== cart.length) { cart = validCart; updateCount(); } cartView.innerHTML = cart.length ? cart.map(function (item) { var product = getProduct(item.id), line = product.price * item.quantity; total += line; return '<div class="cart-row"><strong>' + product.name + '</strong><span>' + money(product.price) + '</span><input class="cart-quantity" data-id="' + item.id + '" type="number" min="1" max="' + product.stock + '" value="' + item.quantity + '"><button class="remove-cart" data-id="' + item.id + '" type="button">Remove</button><strong>' + money(line) + '</strong></div>'; }).join('') + '<div class="cart-total"><strong>Total ' + money(total) + '</strong><a class="btn" href="checkout.html">Checkout</a></div>' : '<p>Your cart is currently empty. <a href="products.html">Explore products</a>.</p>'; }
        var orderView = document.getElementById('orderList'); if (orderView) { var orders = read('orders', []); orderView.innerHTML = orders.length ? orders.map(function (order) { var customer = order.customer || {}; return '<article class="card"><strong>Order ID: #' + order.id + '</strong><p>Store name: ' + (customer.store || 'Not provided') + '</p><p>Person name: ' + (customer.name || 'Not provided') + '</p><p>Mobile No.: ' + (customer.phone || 'Not provided') + '</p>' + (customer.gst ? '<p>GST Number: ' + customer.gst + '</p>' : '') + '<p>' + order.status + ' · ' + money(order.total) + '</p><p>Payment: ' + (order.payment === 'cod' ? 'Cash on Delivery' : order.payment === 'card' ? 'Card' : 'Invoice') + '</p><p><a class="btn" href="invoice.html?id=' + encodeURIComponent(order.id) + '">View invoice</a> <button class="cancel-order btn" data-id="' + order.id + '" type="button">Cancel order</button></p></article>'; }).join('') : '<p>No orders yet. Your completed purchases will appear here.</p>'; }
        var profile = document.getElementById('customerProfile'); if (profile) { var savedProfile = read('customerProfile', {}); Object.keys(savedProfile).forEach(function (key) { if (profile.elements[key]) profile.elements[key].value = savedProfile[key]; }); profile.addEventListener('submit', function (event) { event.preventDefault(); write('customerProfile', Object.fromEntries(new FormData(profile).entries())); document.getElementById('profileStatus').textContent = 'Profile saved'; }); }
        document.querySelectorAll('.add-product').forEach(function (button) { button.addEventListener('click', function () { addToCart(button.dataset.productId, 1); button.textContent = 'Added'; }); });
        document.querySelectorAll('.remove-cart').forEach(function (button) { button.addEventListener('click', function () { cart = cart.filter(function (item) { return item.id !== button.dataset.id; }); updateCount(); location.reload(); }); });
        document.querySelectorAll('.cart-quantity').forEach(function (input) { input.addEventListener('change', function () { var item = cart.find(function (entry) { return entry.id === input.dataset.id; }); item.quantity = Math.max(1, Number(input.value)); updateCount(); location.reload(); }); });
        document.querySelectorAll('.cancel-order').forEach(function (button) { button.addEventListener('click', function () { var orders = read('orders', []), order = orders.find(function (entry) { return entry.id === button.dataset.id; }); if (order) order.status = 'Cancelled'; write('orders', orders); location.reload(); }); });
        var detailAdd = document.getElementById('detailAdd'); if (detailAdd) detailAdd.addEventListener('click', function () { addToCart(detailAdd.dataset.productId, Number(document.getElementById('detailQuantity').value)); detailAdd.textContent = 'Added to cart'; });
        var wishlist = document.getElementById('wishlistToggle'); if (wishlist) wishlist.addEventListener('click', function () { var saved = read('wishlist', []), id = detailAdd.dataset.productId; saved = saved.indexOf(id) >= 0 ? saved.filter(function (item) { return item !== id; }) : saved.concat(id); write('wishlist', saved); wishlist.textContent = saved.indexOf(id) >= 0 ? 'Saved to wishlist' : '♡ Wishlist'; });
        var checkout = document.getElementById('checkoutForm'); if (checkout) checkout.addEventListener('submit', function (event) { event.preventDefault(); if (!checkout.checkValidity() || !cart.length) return; var formData = new FormData(checkout), total = cart.reduce(function (sum, item) { return sum + getProduct(item.id).price * item.quantity; }, 0), orders = read('orders', []), orderId = String(Date.now()).slice(-6), profile = read('customerProfile', {}); orders.unshift({ id: orderId, invoiceNumber: 'INV-' + new Date().getFullYear() + '-' + orderId, createdAt: new Date().toISOString(), total: total, status: 'Processing', items: cart.map(function (item) { var product = getProduct(item.id); return { id: item.id, sellerId: product.sellerId || '', name: product.name, price: product.price, unit: product.unit, quantity: item.quantity }; }), customer: { store: profile.store || '', name: profile.name || formData.get('recipient'), email: profile.email || '', phone: profile.phone || '', gst: profile.gst || '' }, address: { recipient: formData.get('recipient'), company: formData.get('company'), city: formData.get('city'), landmark: formData.get('landmark'), postalCode: formData.get('postalCode'), country: formData.get('country') }, payment: formData.get('payment') }); write('orders', orders); cart = []; updateCount(); location.href = 'orders.html'; });
    });
})();
