(function () {
    var read = function (key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch (error) { return fallback; } };
    var escapeHtml = function (value) { return String(value == null ? '' : value).replace(/[&<>'"]/g, function (character) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]; }); };
    var money = function (value) { return '₹' + Number(value || 0).toFixed(2); };
    var paymentName = function (value) { return value === 'cod' ? 'Cash on Delivery' : value === 'card' ? 'Card' : 'Invoice'; };
    document.addEventListener('DOMContentLoaded', function () {
        var documentView = document.getElementById('invoiceDocument'), query = new URLSearchParams(location.search), id = query.get('id'), sellerId = query.get('sellerId'), activeSeller = read('activeSeller', ''), order = read('orders', []).find(function (entry) { return entry.id === id; });
        if (sellerId && sellerId !== activeSeller) order = null;
        if (!order) { documentView.innerHTML = '<h1>Invoice not found</h1><p><a href="orders.html">Return to orders</a></p>'; return; }
        var invoiceNumber = order.invoiceNumber || 'INV-' + order.id, customer = order.customer || {}, items = sellerId ? (order.items || []).filter(function (item) { return item.sellerId === sellerId; }) : (order.items || []), address = order.address || {}, addressText = typeof address === 'string' ? address : [address.recipient, address.Vendor, address.city, address.landmark, address.postalCode, address.country].filter(Boolean).join(', '), total = sellerId ? items.reduce(function (sum, item) { return sum + Number(item.price || 0) * Number(item.quantity || 0); }, 0) : order.total;
        if (sellerId && !items.length) { documentView.innerHTML = '<h1>Invoice not found</h1><p><a href="../sellerhub/orders.html">Return to orders</a></p>'; return; }
        documentView.innerHTML = '<div class="invoice-header"><div><p class="eyebrow">DailyDrop</p><h1>Invoice</h1><p>Everyday supply, made easier.</p></div><div><p><strong>' + escapeHtml(invoiceNumber) + '</strong></p><p>Issued ' + escapeHtml(new Date(order.createdAt || Date.now()).toLocaleDateString()) + '</p><p>' + escapeHtml(order.status || 'Processing') + '</p></div></div>' +
            '<div class="invoice-meta"><div><p class="section-label">Bill to</p><p><strong>' + escapeHtml(customer.name || 'DailyDrop customer') + '</strong></p><p>' + escapeHtml(customer.email) + '</p><p>' + escapeHtml(customer.phone) + '</p></div><div><p class="section-label">Delivery</p><p>' + escapeHtml(addressText) + '</p><p>Payment: ' + paymentName(order.payment) + '</p></div></div>' +
            '<table class="invoice-table"><thead><tr><th>Item</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>' + items.map(function (item) { var lineTotal = Number(item.price || 0) * Number(item.quantity || 0); return '<tr><td>' + escapeHtml(item.name || item.id) + '<br><small>' + escapeHtml(item.unit || '') + '</small></td><td>' + escapeHtml(item.quantity) + '</td><td>' + money(item.price) + '</td><td>' + money(lineTotal) + '</td></tr>'; }).join('') + '</tbody></table><div class="invoice-total"><strong>Total due</strong><strong>' + money(total) + '</strong></div><div class="invoice-actions"><button class="btn" id="printInvoice" type="button">Print invoice</button><a class="button button-quiet" href="' + (sellerId ? '../sellerhub/orders.html' : 'orders.html') + '">Back to orders</a></div>';
        document.getElementById('printInvoice').addEventListener('click', function () { window.print(); });
    });
})();
